language: node_js
node_js:
  - 5
os:
  - linux
env:
  - NODE_ENV=staging
  - NODE_ENV=production
script:
  - npm run build
after_success:
  - python node_modules/travis-weigh-in/weigh_in.py dist/onfido.min.js
  - chmod ugo+x ./deploy.sh
  - ./deploy.sh
