name: Push to S3

on:
  push:
    branches:
    - feature/one-btn-release-publish-cx-4079

    # tags:
    # - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Build dist
      run: |
        npm install
        npm run build

    - name: Get version
      id: get_version
      run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Get base32 version
      id: get_base32_version
      run: |
        source ./workflows.config  
        echo ::set-env name=BASE32_VERSION::${BASE32_VERSION}

    - name: Upload Base32 to S3
      run: |
        aws s3 cp ./dist s3://${{ secrets.AWS_S3_BUCKET }}/web-sdk-base32-releases/$BASE32_VERSION --recursive --acl public-read
    
    - name: Upload Release to S3
      run: |
        aws s3 cp ./dist s3://${{ secrets.AWS_S3_BUCKET }}/web-sdk-releases/$VERSION/ --recursive --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'

    # - name: Publish to NPM
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}