name: Push to S3

on:
  push:
    branches:
      - feature/one-btn-release-publish-cx-4079

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # - uses: jakejarvis/s3-sync-action@master

    - name: Upload to S3
      run: |
        aws s3 cp ./dist s3://${{ secrets.AWS_S3_BUCKET }}/test-github-actions/ --recursive
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'

      # with:
      #   args: --exclude "*.html"
      # env:
      #   AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   SOURCE_DIR: './dist'
      #   DEST_DIR: 'test-github-actions/'